language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm@latest
before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate
env:
  global:
    - DEBUG="sails-orientdb:*,-sails-orientdb:*:debug"
  matrix:
    - ORIENTDB_VERSION=1.7.10
    - ORIENTDB_VERSION=2.0.2
addons:
  code_climate:
    repo_token: da62631f47073c66af8ef169090acb1f49a9aa332f3a449ef04cbf6b58c0c446