language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
  - ./ci/initialize-ci.sh $ORIENTDB_VERSION
env:
  - ORIENTDB_VERSION=1.7.10
  - ORIENTDB_VERSION=2.0-SNAPSHOT
deploy:
  provider: npm
  email: npm@appscot.com
  api_key:
    secure: ijbUZx+cKKPD3FADy1wBzEs0OkoRDKMu8Wdra/Zrs4Ir+YkUsh7xPoyPh7C37uKuwtCbC1g+W5Mq1ZNlcIkI9lAylL/9H/2G2SPIs2PMp5OW1rbuAWmbyCapVGBT4OuWh8tRvhxBPUOkT3Z9tkUBaU6ULZezsmPnf14mS3pTJMI=
  on:
    tags: true
    repo: appscot/waterline-orientdb
